AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation Template to onboard CREE8 with Admin Access'

Parameters:
  CREE8AccountId:
    Type: String
    Default: '321267487758'
    Description: 'CREE8 Account ID'
    AllowedPattern: '^\d{12}$'
    ConstraintDescription: 'Must be a valid 12-digit AWS account ID'

Resources:
  CREE8AdminRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'CREE8-Admin-Role'
      Description: 'Cross-Account Role for CREE8 Platform Administration'
      MaxSessionDuration: 28800
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/job-function/Billing'
        - 'arn:aws:iam::aws:policy/AdministratorAccess'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${CREE8AccountId}:root'
            Action: 'sts:AssumeRole'

Outputs:
  RoleARN:
    Description: 'ARN of CREE8 Admin Role to share with the CREE8 Team'
    Value: !GetAtt CREE8AdminRole.Arn
